spring.application.name=AI-NextGen-Hacks
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.rgkngmdpoylnupcebqlf&password=HarishSathiya@07
spring.datasource.username=postgres.rgkngmdpoylnupcebqlf
spring.datasource.password=HarishSathiya@07
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Ignore spring security by default for api
spring.security.user.name=admin
spring.security.user.password=admin
